apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "renovate.fullname" . }}
  labels:
    {{- include "renovate.labels" . | nindent 4 }}
spec:
  backoffLimit:
    {{- toYaml .Values.backoffLimit | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "renovate.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: {{ include "renovate.fullname" . }}
            mountPath: /usr/src/app/config.js
            subPath: config.js
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Never
      volumes:
        - name: {{ include "renovate.fullname" . }}
          configMap:
            name: {{ include "renovate.fullname" . }}
