name: Test

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Helm
        uses: azure/setup-helm@v1

      - name: Helm lint
        run: helm lint renovate

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0-alpha.2
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
